# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x0b\x43omplexType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1c\n\x0bLongRequest\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1d\n\x0cLongResponse\x12\r\n\x05value\x18\x01 \x01(\x03\"s\n\x11\x45ightLongsRequest\x12\n\n\x02v1\x18\x01 \x01(\x03\x12\n\n\x02v2\x18\x02 \x01(\x03\x12\n\n\x02v3\x18\x03 \x01(\x03\x12\n\n\x02v4\x18\x04 \x01(\x03\x12\n\n\x02v5\x18\x05 \x01(\x03\x12\n\n\x02v6\x18\x06 \x01(\x03\x12\n\n\x02v7\x18\x07 \x01(\x03\x12\n\n\x02v8\x18\x08 \x01(\x03\"\x1e\n\rStringRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0eStringResponse\x12\r\n\x05value\x18\x01 \x01(\t\"7\n\x0e\x43omplexRequest\x12%\n\x07\x63omplex\x18\x01 \x01(\x0b\x32\x14.service.ComplexType\"8\n\x0f\x43omplexResponse\x12%\n\x07\x63omplex\x18\x01 \x01(\x0b\x32\x14.service.ComplexType2\xcd\x02\n\x0bTestService\x12@\n\x0eNoArgsNoReturn\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x07OneLong\x12\x14.service.LongRequest\x1a\x15.service.LongResponse\x12?\n\nEightLongs\x12\x1a.service.EightLongsRequest\x1a\x15.service.LongResponse\x12<\n\tOneString\x12\x16.service.StringRequest\x1a\x17.service.StringResponse\x12\x45\n\x10\x43omplexOperation\x12\x17.service.ComplexRequest\x1a\x18.service.ComplexResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLEXTYPE']._serialized_start=55
  _globals['_COMPLEXTYPE']._serialized_end=95
  _globals['_LONGREQUEST']._serialized_start=97
  _globals['_LONGREQUEST']._serialized_end=125
  _globals['_LONGRESPONSE']._serialized_start=127
  _globals['_LONGRESPONSE']._serialized_end=156
  _globals['_EIGHTLONGSREQUEST']._serialized_start=158
  _globals['_EIGHTLONGSREQUEST']._serialized_end=273
  _globals['_STRINGREQUEST']._serialized_start=275
  _globals['_STRINGREQUEST']._serialized_end=305
  _globals['_STRINGRESPONSE']._serialized_start=307
  _globals['_STRINGRESPONSE']._serialized_end=338
  _globals['_COMPLEXREQUEST']._serialized_start=340
  _globals['_COMPLEXREQUEST']._serialized_end=395
  _globals['_COMPLEXRESPONSE']._serialized_start=397
  _globals['_COMPLEXRESPONSE']._serialized_end=453
  _globals['_TESTSERVICE']._serialized_start=456
  _globals['_TESTSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
